### ISSUE TITLE
rtree: issue reading vector of strings

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#781]
It seems the current reading tools is not able to read branches of `vector<string>` (if that makes sense). And it seems the line
```go
obj, err := f.Get("sumWeights")
```
creates this error message:
```
panic: rtree: unknown streamer element: &rdict.StreamerSTL{StreamerElement:rdict.StreamerElement{named:rbase.Named{obj:rbase.Object{ID:0x0, Bits:0x3000000}, name:"vector<string>", title:""}, etype:500, esize:24, arrlen:0, arrdim:0, maxidx:[5]int32{0, 0, 0, 0, 0}, offset:0, ename:"vector<TString>", xmin:0, xmax:0, factor:0}, vtype:1, ctype:65}
```

I have put an example ROOT file with 2 entries here: https://cernbox.cern.ch/index.php/s/kw2HoLLhp4AorYd

**Comment by rmadar** [comment]
Looking at it more closely, it seems this tree is a bit weird. Indeed, apparently the `string` branches seems to no be read properly - while I know this type is already implemented. 

Here is a minimal example reproducing the bug (using https://github.com/go-hep/hep/commit/98270f3ff72b51f40a1e41cfddab50c8529a0b8b), where the following code

```go
func main(){                                                       
                                                                   
        // Open ROOT file                                          
        f, err := groot.Open("vectorStringExample.root")           
        if err != nil {                                            
                log.Fatal(err)                                     
        }                                                          
                                                                   
        // Get weird tree                                          
        _, err = f.Get("sumWeights")                               
        if err != nil {                                            
                log.Fatal(err)                                     
        }                                                          
} 
```
gives the following panic message:
```
panic: rtree: could not find streamer for branch "generators": riofs: no streamer for "string"

goroutine 1 [running]:
go-hep.org/x/hep/groot/rtree.(*ttree).UnmarshalROOT(0xc000001980, 0xc000111c20, 0xc000001980, 0x7f425d040388)
	/users/divers/atlas/madar/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200721152530-98270f3ff72b/groot/rtree/tree.go:470 +0x1444
go-hep.org/x/hep/groot/riofs.(*Key).Object(0xc00014b2b0, 0x0, 0x0, 0x0, 0x1)
	/users/divers/atlas/madar/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200721152530-98270f3ff72b/groot/riofs/key.go:369 +0x2dd
go-hep.org/x/hep/groot/riofs.(*tdirectoryFile).Get(0xc0000ff998, 0x84b768, 0xa, 0x0, 0x0, 0x0, 0x0)
	/users/divers/atlas/madar/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200721152530-98270f3ff72b/groot/riofs/dir.go:389 +0x2e1
go-hep.org/x/hep/groot/riofs.(*File).Get(...)
	/users/divers/atlas/madar/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200721152530-98270f3ff72b/groot/riofs/file.go:840
main.main()
	/users/divers/atlas/madar/home2/tmp/gotest/main.go:19 +0xb7
exit status 2

```

**Comment by sbinet** [comment]
thanks.
should be fixed w/ https://github.com/go-hep/hep/pull/783

**Comment by rmadar** [comment]
Thanks it works for the `string` branch in the simple code, but it still doesn't work for the original reported issue.

I wonder if there is not something special during the creation of my input file (which contains several trees, directories, etc ...). Indeed, when I load the input file in ROOT, I get this:
```
[madar@clratlserv01]:home2>root weirdRootFile.root 
root [0] 
Attaching file weirdRootFile.root as _file0...
ReadStreamerInfo, class:string, illegal uid=-2
(TFile *) 0x40bc8f0
root [1] 
```
The **ReadStreamerInfo, class:string, illegal uid=-2** seems relevant here ...

Here are few test that I have made:
 1. If I extract the tree `sumWeights` in another file with a ROOT macro, and I run the go code on this new file, it works.
 2. If I read another tree in the original input file, it works.

In case you think it something worth it to look at, I have put a relatively small input file (20 Mo) here: https://cernbox.cern.ch/index.php/s/aBL1s24hmA6gvFW

**Comment by sbinet** [comment]
root-dump chokes on the `weirdRootFile.root` with:

```
key[006]: AnalysisTracking;1 "" (TTree)
panic: rtree: could not create rstreamer for rleaf "jsonData"

goroutine 1 [running]:
go-hep.org/x/hep/groot/rtree.newRLeafElem(0xc00007c1a0, 0xc000433958, 0x8, 0xc000433988, 0x8, 0xa6e200, 0x1101810, 0x0, 0x0, 0xd582a0, ...)
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/rtree/rleaf.go:165 +0x84f
go-hep.org/x/hep/groot/rtree.rleafFrom(0xd582a0, 0xc00007c1a0, 0xc000433958, 0x8, 0xc000433988, 0x8, 0xa6e200, 0x1101810, 0x0, 0x0, ...)
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/rtree/rleaf.go:122 +0x212
go-hep.org/x/hep/groot/rtree.newRTree(0xc0004e2600, 0xc0002e7db0, 0x1, 0x1, 0x2, 0x0, 0x2, 0x1)
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/rtree/reader.go:310 +0x429
go-hep.org/x/hep/groot/rtree.newReader(0xd46ba0, 0xc0004e2600, 0xc0002e7db0, 0x1, 0x1, 0x2, 0x0, 0x2, 0x0, 0x0)
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/rtree/reader.go:255 +0x205
go-hep.org/x/hep/groot/rtree.NewReader(0xd46ba0, 0xc0004e2600, 0xc0002e7db0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x500771, 0xc00007c000, ...)
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/rtree/reader.go:66 +0x210
go-hep.org/x/hep/groot/rcmd.(*dumpCmd).dumpTree(0xc0002830a0, 0xd46ba0, 0xc0004e2600, 0x0, 0x0)
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/rcmd/dump.go:122 +0xb5
go-hep.org/x/hep/groot/rcmd.(*dumpCmd).dumpObj(0xc0002830a0, 0x7f3b200bc040, 0xc0004e2600, 0x0, 0x0)
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/rcmd/dump.go:82 +0x1ad
go-hep.org/x/hep/groot/rcmd.(*dumpCmd).dumpDir(0xc0002830a0, 0xd44280, 0xc00029ac80, 0x0, 0x0)
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/rcmd/dump.go:64 +0x3ae
go-hep.org/x/hep/groot/rcmd.Dump(0xd33aa0, 0xc00024d140, 0x7ffc5de91818, 0x28, 0xc00019fe01, 0xb83c58, 0x0, 0x0)
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/rcmd/dump.go:44 +0x16e
main.dump(0xd33aa0, 0xc00024d140, 0x7ffc5de91818, 0x28, 0x1, 0x0, 0xb569c2)
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/cmd/root-dump/main.go:123 +0xf0
main.main()
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/cmd/root-dump/main.go:113 +0x2a5
```

and indeed, there's no `jsonData` streamer in that ROOT file.
(not sure what groot can do about that, though.)

now, with:
```
$> root-dump -name=sumWeights weirdRootFile.root
[...]
panic: rtree: could not create rstreamer for rleaf "generators"

goroutine 1 [running]:
go-hep.org/x/hep/groot/rtree.newRLeafElem(0xc000129ba0, 0xc00027fab0, 0xa, 0xc00027fb00, 0xa, 0xa6e200, 0x1101810, 0x0, 0x0, 0xd583a0, ...)
	/home/binet/tmp/go/src/go-hep.org/x/hep/groot/rtree/rleaf.go:172 +0xb4f
[...]
```

and indeed, still no associated streamer for the type "generators" in that file either...

do you know how they were created?

**Comment by rmadar** [comment]
These files are created with an ATLAS-internal framework called `AnalysisTop`, based on `AnalysisBase` - which is the "basic" fw to read xAOD (if I am not wrong).

There is something I don't get: when I print the `sumWeights` tree content it says that the branch `generator` is a `string`:
```
root [2] sumWeights->Print()
...
*............................................................................*
*Br    2 :generators : string                                                *
*Entries :        2 : Total  Size=        713 bytes  File Size  =        204 *
*Baskets :        2 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    3 :AMITag    : string                                                 *
*Entries :        2 : Total  Size=        771 bytes  File Size  =        246 *
*Baskets :        2 : Basket Size=      32000 bytes  Compression=   1.13     *
*............................................................................*
*Br    4 :totalEventsWeighted : totalEventsWeighted/F                        *
*Entries :        2 : Total  Size=        733 bytes  File Size  =        192 *
*Baskets :        2 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    5 :totalEventsWeighted_mc_generator_weights : vector<float>           *
*Entries :        2 : Total  Size=       1819 bytes  File Size  =       1148 *
*Baskets :        2 : Basket Size=      32000 bytes  Compression=   1.04     *
*............................................................................*
*Br    6 :names_mc_generator_weights : vector<string>                        *
*Entries :        2 : Total  Size=       5355 bytes  File Size  =        956 *
*Baskets :        2 : Basket Size=      32000 bytes  Compression=   5.00     *
*............................................................................*
...
```
So it shoudn't be a problem ... ?

Concerning the JSON format, this is basically the analysis configuration which is stored in the output. And I think we can leave this aside for now ... (I have never used it so far).

**Comment by rmadar** [comment]
OK I have pursued the investigations ... and this is even worth. Two ways to extract `sumWeights`, leading to very different behavior of go-hep:
  1. opening the input file, grabing the tree and saving it in another root file: go-hep crashes on it
  2. opening the input file, grabing the tree, **create a new tree with `outTree = inTree->TreeCopy()`**, saving `ouTree` in a new file. go-hep works fine.

So I definitely think there is something weird in the creation of the ntuple (that ROOT is able to tolerate somehow),

**Comment by sbinet** [comment]
FYI, #801 is able to `root-dump` your whole `weirdRootFile.root` :)
